# Generated by Django 5.1.1 on 2025-06-18 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart_latesttrade_cart_latesttradeamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chat_sequence', models.IntegerField()),
                ('chat_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('gps_sequence', models.IntegerField()),
                ('gps_coordinates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('last_seen_location', models.TextField(blank=True, default='', null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='scanner',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='location',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.robot'),
        ),
        migrations.AddField(
            model_name='chat',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.robot'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
    ]
