# Generated by Django 5.1.1 on 2025-06-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chat_location_robot_remove_cart_scanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rag', models.TextField(default='')),
            ],
        ),
    ]
